### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by w4zir** [dataquestio/loan-prediction#1]
I am following your Machine learning project but get the following error when execute assemle.py. I know its index out of bound error but I cant figure out where?

python assemble.py
Traceback (most recent call last):
  File "assemble.py", line 87, in <module>
    concatenate("Performance")
  File "assemble.py", line 77, in concatenate
    data = pd.read_csv(os.path.join(settings.DATA_DIR, f), sep="|", header=None, names=HEADERS[prefix], index_col=False)
  File "/home/khan/anaconda3/envs/mllearn/lib/python3.6/site-packages/pandas/io/parsers.py", line 646, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/khan/anaconda3/envs/mllearn/lib/python3.6/site-packages/pandas/io/parsers.py", line 401, in _read
    data = parser.read()
  File "/home/khan/anaconda3/envs/mllearn/lib/python3.6/site-packages/pandas/io/parsers.py", line 939, in read
    ret = self._engine.read(nrows)
  File "/home/khan/anaconda3/envs/mllearn/lib/python3.6/site-packages/pandas/io/parsers.py", line 1508, in read
    data = self._reader.read(nrows)
  File "pandas/parser.pyx", line 848, in pandas.parser.TextReader.read (pandas/parser.c:10415)
  File "pandas/parser.pyx", line 870, in pandas.parser.TextReader._read_low_memory (pandas/parser.c:10691)
  File "pandas/parser.pyx", line 947, in pandas.parser.TextReader._read_rows (pandas/parser.c:11728)
  File "pandas/parser.pyx", line 1023, in pandas.parser.TextReader._convert_column_data (pandas/parser.c:12805)
  File "pandas/parser.pyx", line 1289, in pandas.parser.TextReader._get_column_name (pandas/parser.c:17512)
IndexError: list index out of range

**Comment by VikParuchuri** [comment]
I haven't seen this particular issue, but here are some ideas for what it could be:

* Verify that the data is there by opening it and reading it with `open` and `.read()`.
* Try removing the `names` keyword arg -- the data may have more/less names than it expects.  It's possible that the format of the data has changed recently.

**Comment by w4zir** [comment]
Two features were missing in the header for Performance.txt that results in this error. I have added them to assemble.py and opened a pull request.
